"""empty message

Revision ID: 9506ffb8da12
Revises: df0b220eba54
Create Date: 2020-10-07 00:05:49.674205

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9506ffb8da12"
down_revision = "df0b220eba54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
