"""empty message

Revision ID: df0b220eba54
Revises: e587bcaef19b
Create Date: 2020-10-06 23:56:27.770365

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "df0b220eba54"
down_revision = "e587bcaef19b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currency", sa.Column("rate", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("currency", "rate")
    # ### end Alembic commands ###
