"""empty message

Revision ID: e587bcaef19b
Revises: 1d55f59030d6
Create Date: 2020-10-06 23:02:45.093011

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e587bcaef19b"
down_revision = "1d55f59030d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("exchange_code", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency")
    # ### end Alembic commands ###
